### ISSUE TITLE
Revoke Certificate

### ISSUE THREAD

**Issue by adamkdean** [adamkdean/zerossl#1]
After speaking with ZeroSSL, the revoke certificate endpoint has now been documented: https://zerossl.com/documentation/api/revoke-certificate/

This will need to be implemented into the API wrapper.

**Comment by alisson-acioli** [comment]
Hello, do you have a plan for implementation?

**Comment by adamkdean** [comment]
Hi @alisson-acioli, there's no current plan to implement this myself (no free time currently) but I'll be happy to review PRs if a member of the community wishes to contribute

**Comment by alisson-acioli** [comment]
I understand, if I may, I will help with that. This week I will send you some PRs with useful modifications and updates to your project. ZeroSSL has had some updates this past month and their project is very good and I would like to implement it. I will send PRs to you soon. Thanks for listening.

**Comment by adamkdean** [comment]
Many thanks @alisson-acioli for your contributions to the project

**Comment by alisson-acioli** [comment]
@adamkdean 

It was a pleasure to help you.

Any updates to the ZeroSSL API will help again.
